version: '3'
services:
  # App server
  web:
    build:
      context: ../..
      dockerfile: docker/app/dev.Dockerfile
    volumes:
      - ../../server:/app
    environment:
      VIRTUAL_HOST: ttu.localhost, *.ttu.localhost
      HTTPS_METHOD: noredirect
    network_mode: bridge
    links:
      - mysql
      - redis

  # MySQL
  mysql:
    network_mode: bridge
    ports:
      - 43306:3306
  
  # Redis
  redis:
    network_mode: bridge